In [68]:
from sklearn import svm, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import glob, os.path, re
import random

matplotlib.rcParams['axes.unicode_minus'] = False 
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # : windows 사용자용
matplotlib.rcParams['font.size'] = '10'

In [69]:
import requests
files = 'm.csv'
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
res = requests.get(url)
# res.text
with open(files,'w',encoding='utf-8-sig') as f:
    f.write(res.text)

In [ ]:
# 독버섯과 식용버섯을 분류하는 알고리즘을 구현
# p - poisonous
# e - eatable

In [70]:
df = pd.read_csv('m.csv',header=None)
df

     0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1     e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2     e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3     p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4     e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  e  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8120  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8121  e  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8122  p  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8123  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[8124 rows x 23 columns]

In [ ]:
df.iloc[0,0]
ord('p')

112

In [71]:
# 2중 for문 사용
for i in range(len(df)):
    for j in range(len(df.columns)):
        l_pos = df.iloc[i,j]
        ord(l_pos)
        df.iloc[i,j] = ord(l_pos)
df

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,112,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,101,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,101,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,112,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,101,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,101,107,115,110,102,110,97,99,98,121,...,115,111,111,112,111,111,112,98,99,108
8120,101,120,115,110,102,110,97,99,98,121,...,115,111,111,112,110,111,112,98,118,108
8121,101,102,115,110,102,110,97,99,98,110,...,115,111,111,112,111,111,112,98,99,108
8122,112,107,121,110,102,121,102,99,110,98,...,107,119,119,112,119,111,101,119,118,108
8123,101,120,115,110,102,110,97,99,98,121,...,115,111,111,112,111,111,112,111,99,108

### iterrows()를 사용하여 아스키코드로 변환 -> target, test 데이터를 분리하여 사용

In [72]:
df.head(3)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,112,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,101,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,101,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109

In [73]:
target = [] # 첫번째 컬럼이 target
data = []
# df.loc[0,1:]

In [ ]:
# 아스키 코드로 변환
# df.iterrows()[0]   :   enumerate를 섞은 것으로 보면 됨
# for row_index, row in df.iterrows() :
#     target.append(row.loc[0])    # target 결과값
#     row_data = []
#     for v in row.loc[1:]:
#         row_data.append(ord(v))  # 1줄의 데이터를 숫자로 변경해서 list에 저장
        
#     data.append(row_data)        # 1줄 리스트를 다시 리스트에 추가
    
# df2 = pd.DataFrame(data)
# df2


# append 사용
# data = df.iloc[i,1:]
# d_list = []
# all_list= [] # 리스트 안의 리스트 형태
# for d in data :
#     d_list.append(ord(d))
# d_list

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# 데이터 전처리 -  train, test 세트 구현
train_input, test_input, train_target, test_target = train_test_split(data, target)
 

# 데이터 학습시키기
# clf = RandomForestClassifier()
# clf = svm.SVC()
clf = KNeighborsClassifier()
clf.fit(train_input, train_target)

# 데이터 예측하기
predict = clf.predict(test_input)
print("결과값 :", predict)

# 정답률
score = clf.score(test_input, test_target)
print("정답률 :", score)

### one_hot_encoding

In [75]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,112,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,101,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,101,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,112,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,101,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [ ]:
# 종류는 컬럼별로 카운트
# 실제 컬럼은 22개 -> 문자의 다른 컬럼들은 12개

In [76]:
[0]*12

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
# v = 0일 때, 22개의 데이터가 넘어옴
# x	s	n	t	p	f	c	n	k	...	s	w	w	p	w	o	p	k	s	u

In [77]:
target = [] 
data = []
attr_list = []
for row_index, row in df.iterrows() :
    target.append(row.loc[0])    # target 결과값
    row_data = []
    for col, v in enumerate(row.loc[1:]):
        if row_index == 0:
            attr = {"dic":{},"cnt":0}  # cnt : 컬럼별 다른 문자의 수 -> 12개
            attr_list.append(attr)
        else:
            attr = attr_list[col]   
        
        # 원핫인코딩 변환    
        d = [0]*12
        if v in attr["dic"]:
            idx = attr["dic"][v]
            # print(idx)
        else:
            idx =  attr['cnt']
            attr['dic'][v] = idx
            # print(attr['dic'][v])
            attr["cnt"] += 1
             
        d[idx] = 1
        row_data += d            # 원핫인코딩의 데이터 저장파일 -데이터의 가중치 때문에 정답률이 다를 수 있음
        
    data.append(row_data)        # 1줄 리스트를 다시 리스트에 추가
data[0]
    
# df2 = pd.DataFrame(data)
# df2

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]