In [28]:
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import requests
import oracledb

matplotlib.rcParams['axes.unicode_minus'] = False 
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # : windows 사용자용
matplotlib.rcParams['font.size'] = '10'

In [29]:
url = "https://api.odcloud.kr/api/3051434/v1/uddi:a9238a42-556e-4feb-8e2e-f89c7ff72fb9_201706131814?page=1&perPage=10&serviceKey=W9pkpJL4PH5n%2B0CFILqfVpnIOUvDB1hoKMqpTvqBn2md6uUGEWP0nI3zoa6uOJnnQ4tDrntFwqBNAz0JRdZ7RQ%3D%3D"
res = requests.get(url)
res.text

'{"currentCount":10,"data":[{"기관부담금(천원)":"5390627489","시도":"전국","입내원일수":"96329691","종별":"1종","진료건수":"61005932","진료실인원":"1147555","진료일수":"478676699","진료형태":"계","총진료비(천원)":"5443835740"},{"기관부담금(천원)":"3031441055","시도":"전국","입내원일수":"37763697","종별":"1종","진료건수":"2226345","진료실인원":"365012","진료일수":"43130721","진료형태":"입원","총진료비(천원)":"3031986806"},{"기관부담금(천원)":"1512928134","시도":"전국","입내원일수":"38854295","종별":"1종","진료건수":"39067888","진료실인원":"1101057","진료일수":"110371962","진료형태":"외래","총진료비(천원)":"1558048973"},{"기관부담금(천원)":"846258300","시도":"전국","입내원일수":"19711699","종별":"1종","진료건수":"19711699","진료실인원":"1028970","진료일수":"325174016","진료형태":"약국","총진료비(천원)":"853799960"},{"기관부담금(천원)":"779748814","시도":"서울","입내원일수":"13185805","종별":"1종","진료건수":"9514703","진료실인원":"179395","진료일수":"76975028","진료형태":"계","총진료비(천원)":"788163801"},{"기관부담금(천원)":"382328645","시도":"서울","입내원일수":"3997689","종별":"1종","진료건수":"241674","진료실인원":"47024","진료일수":"4772046","진료형태":"입원","총진료비(천원)":"382416025"},{"기관부담금(천원)":"260504054","시도":"서울","입내원일수":"6161616","종별":"1종","진료건수":"6246529","진료실인원":"173783","진료일수":"16971787","진료형태":"외래","총진료비(천원)":"267684499"},{"기관부담금(천원)":"136916115","시도":"서울","입내원일수":"3026500","종별":"1종","진료건수":"3026500","진료실인원":"162602","진료일수":"55231195","진료형태":"약국","총진료비(천원)":"138063277"},{"기관부담금(천원)":"567881423","시도":"부산","입내원일수":"10358662","종별":"1종","진료건수":"6091668","진료실인원":"107768","진료일수":"47018904","진료형태":"계","총진료비(천원)":"573206562"},{"기관부담금(천원)":"342524365","시도":"부산","입내원일수":"4513025","종별":"1종","진료건수":"248460","진료실인원":"37361","진료일수":"4978182","진료형태":"입원","총진료비(천원)":"342575876"}],"matchCount":216,"page":1,"perPage":10,"totalCount":216}\n'

In [30]:
res_json = res.json()
res_json

{'currentCount': 10,
 'data': [{'기관부담금(천원)': '5390627489',
   '시도': '전국',
   '입내원일수': '96329691',
   '종별': '1종',
   '진료건수': '61005932',
   '진료실인원': '1147555',
   '진료일수': '478676699',
   '진료형태': '계',
   '총진료비(천원)': '5443835740'},
  {'기관부담금(천원)': '3031441055',
   '시도': '전국',
   '입내원일수': '37763697',
   '종별': '1종',
   '진료건수': '2226345',
   '진료실인원': '365012',
   '진료일수': '43130721',
   '진료형태': '입원',
   '총진료비(천원)': '3031986806'},
  {'기관부담금(천원)': '1512928134',
   '시도': '전국',
   '입내원일수': '38854295',
   '종별': '1종',
   '진료건수': '39067888',
   '진료실인원': '1101057',
   '진료일수': '110371962',
   '진료형태': '외래',
   '총진료비(천원)': '1558048973'},
  {'기관부담금(천원)': '846258300',
   '시도': '전국',
   '입내원일수': '19711699',
   '종별': '1종',
   '진료건수': '19711699',
   '진료실인원': '1028970',
   '진료일수': '325174016',
   '진료형태': '약국',
   '총진료비(천원)': '853799960'},
  {'기관부담금(천원)': '779748814',
   '시도': '서울',
   '입내원일수': '13185805',
   '종별': '1종',
   '진료건수': '9514703',
   '진료실인원': '179395',
   '진료일수': '76975028',
   '진료형태': '계',
   '총진료비(천원)': '788163801'},
  {'기관부담금(천원)': '382328645',
   '시도': '서울',
   '입내원일수': '3997689',
   '종별': '1종',
   '진료건수': '241674',
   '진료실인원': '47024',
   '진료일수': '4772046',
   '진료형태': '입원',
   '총진료비(천원)': '382416025'},
  {'기관부담금(천원)': '260504054',
   '시도': '서울',
   '입내원일수': '6161616',
   '종별': '1종',
   '진료건수': '6246529',
   '진료실인원': '173783',
   '진료일수': '16971787',
   '진료형태': '외래',
   '총진료비(천원)': '267684499'},
  {'기관부담금(천원)': '136916115',
   '시도': '서울',
   '입내원일수': '3026500',
   '종별': '1종',
   '진료건수': '3026500',
   '진료실인원': '162602',
   '진료일수': '55231195',
   '진료형태': '약국',
   '총진료비(천원)': '138063277'},
  {'기관부담금(천원)': '567881423',
   '시도': '부산',
   '입내원일수': '10358662',
   '종별': '1종',
   '진료건수': '6091668',
   '진료실인원': '107768',
   '진료일수': '47018904',
   '진료형태': '계',
   '총진료비(천원)': '573206562'},
  {'기관부담금(천원)': '342524365',
   '시도': '부산',
   '입내원일수': '4513025',
   '종별': '1종',
   '진료건수': '248460',
   '진료실인원': '37361',
   '진료일수': '4978182',
   '진료형태': '입원',
   '총진료비(천원)': '342575876'}],
 'matchCount': 216,
 'page': 1,
 'perPage': 10,
 'totalCount': 216}

In [31]:
datas = res_json["data"]
datas

[{'기관부담금(천원)': '5390627489',
  '시도': '전국',
  '입내원일수': '96329691',
  '종별': '1종',
  '진료건수': '61005932',
  '진료실인원': '1147555',
  '진료일수': '478676699',
  '진료형태': '계',
  '총진료비(천원)': '5443835740'},
 {'기관부담금(천원)': '3031441055',
  '시도': '전국',
  '입내원일수': '37763697',
  '종별': '1종',
  '진료건수': '2226345',
  '진료실인원': '365012',
  '진료일수': '43130721',
  '진료형태': '입원',
  '총진료비(천원)': '3031986806'},
 {'기관부담금(천원)': '1512928134',
  '시도': '전국',
  '입내원일수': '38854295',
  '종별': '1종',
  '진료건수': '39067888',
  '진료실인원': '1101057',
  '진료일수': '110371962',
  '진료형태': '외래',
  '총진료비(천원)': '1558048973'},
 {'기관부담금(천원)': '846258300',
  '시도': '전국',
  '입내원일수': '19711699',
  '종별': '1종',
  '진료건수': '19711699',
  '진료실인원': '1028970',
  '진료일수': '325174016',
  '진료형태': '약국',
  '총진료비(천원)': '853799960'},
 {'기관부담금(천원)': '779748814',
  '시도': '서울',
  '입내원일수': '13185805',
  '종별': '1종',
  '진료건수': '9514703',
  '진료실인원': '179395',
  '진료일수': '76975028',
  '진료형태': '계',
  '총진료비(천원)': '788163801'},
 {'기관부담금(천원)': '382328645',
  '시도': '서울',
  '입내원일수': '3997689',
  '종별': '1종',
  '진료건수': '241674',
  '진료실인원': '47024',
  '진료일수': '4772046',
  '진료형태': '입원',
  '총진료비(천원)': '382416025'},
 {'기관부담금(천원)': '260504054',
  '시도': '서울',
  '입내원일수': '6161616',
  '종별': '1종',
  '진료건수': '6246529',
  '진료실인원': '173783',
  '진료일수': '16971787',
  '진료형태': '외래',
  '총진료비(천원)': '267684499'},
 {'기관부담금(천원)': '136916115',
  '시도': '서울',
  '입내원일수': '3026500',
  '종별': '1종',
  '진료건수': '3026500',
  '진료실인원': '162602',
  '진료일수': '55231195',
  '진료형태': '약국',
  '총진료비(천원)': '138063277'},
 {'기관부담금(천원)': '567881423',
  '시도': '부산',
  '입내원일수': '10358662',
  '종별': '1종',
  '진료건수': '6091668',
  '진료실인원': '107768',
  '진료일수': '47018904',
  '진료형태': '계',
  '총진료비(천원)': '573206562'},
 {'기관부담금(천원)': '342524365',
  '시도': '부산',
  '입내원일수': '4513025',
  '종별': '1종',
  '진료건수': '248460',
  '진료실인원': '37361',
  '진료일수': '4978182',
  '진료형태': '입원',
  '총진료비(천원)': '342575876'}]

In [32]:
df = pd.DataFrame(datas)
df

    기관부담금(천원)  시도     입내원일수  종별      진료건수    진료실인원       진료일수 진료형태    총진료비(천원)
0  5390627489  전국  96329691  1종  61005932  1147555  478676699    계  5443835740
1  3031441055  전국  37763697  1종   2226345   365012   43130721   입원  3031986806
2  1512928134  전국  38854295  1종  39067888  1101057  110371962   외래  1558048973
3   846258300  전국  19711699  1종  19711699  1028970  325174016   약국   853799960
4   779748814  서울  13185805  1종   9514703   179395   76975028    계   788163801
5   382328645  서울   3997689  1종    241674    47024    4772046   입원   382416025
6   260504054  서울   6161616  1종   6246529   173783   16971787   외래   267684499
7   136916115  서울   3026500  1종   3026500   162602   55231195   약국   138063277
8   567881423  부산  10358662  1종   6091668   107768   47018904    계   573206562
9   342524365  부산   4513025  1종    248460    37361    4978182   입원   342575876

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기관부담금(천원)  10 non-null     object
 1   시도         10 non-null     object
 2   입내원일수      10 non-null     object
 3   종별         10 non-null     object
 4   진료건수       10 non-null     object
 5   진료실인원      10 non-null     object
 6   진료일수       10 non-null     object
 7   진료형태       10 non-null     object
 8   총진료비(천원)   10 non-null     object
dtypes: object(9)
memory usage: 852.0+ bytes

In [12]:
df['진료건수']

0    61005932
1     2226345
2    39067888
3    19711699
4     9514703
5      241674
6     6246529
7     3026500
8     6091668
9      248460
Name: 진료건수, dtype: object

In [17]:
df['진료실인원'].astype(int).sum()

4350527

In [19]:
# 시도 : 서울, 총진료비(천원) 합계

filt = df[df['시도'] == '서울']
filt['총진료비(천원)'].astype(int).sum()

# df[df['시도'] == '서울']['총진료비(천원)'].astype(int).sum()

1576327602

In [35]:
# 지역별 총진료비 합계
# int는 가능한 단위가 있음(21억) : error type - Python int too large to convert to C long => float로 변경해 주어야 함
df['총진료비(천원)'] = df['총진료비(천원)'].astype(float)
df.groupby('시도')['총진료비(천원)'].sum()  # e+10 : 10의 10승

시도
부산    9.157824e+08
서울    1.576328e+09
전국    1.088767e+10
Name: 총진료비(천원), dtype: float64